# Generated by Django 5.2.8 on 2025-11-09 01:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_remove_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MEDICO', 'Médico'), ('RECEPCIONISTA', 'Recepcionista'), ('PACIENTE', 'Paciente')], default='RECEPCIONISTA', max_length=20, verbose_name='Rol'),
        ),
    ]
