# Generated by Django 5.2.8 on 2025-11-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('identificacion', models.CharField(max_length=20, unique=True, verbose_name='Identificación')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto (teléfono o email)')),
                ('eps', models.CharField(blank=True, max_length=100, null=True, verbose_name='EPS / Aseguradora de salud')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
