# Generated by Django 5.2.8 on 2025-11-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='EPS / Aseguradora')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código EPS')),
                ('contacto', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo de contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'EPS',
                'verbose_name_plural': 'EPS / Aseguradoras',
                'db_table': 'eps',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='paciente',
            name='eps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.eps', verbose_name='EPS / Aseguradora de salud'),
        ),
    ]
