# Generated by Django 5.2.8 on 2025-11-13 23:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_eps_alter_paciente_eps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_prestador', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código del Prestador')),
                ('nit_prestador', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIT')),
                ('direccion_prestador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono_prestador', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('web_prestador', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('email_prestador', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso')),
                ('hora_ingreso', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de Ingreso')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha Cierre HC')),
                ('numero_historia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro. Historia')),
                ('tipo_historia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Historia')),
                ('motivo_consulta', models.TextField(blank=True, null=True, verbose_name='Motivo de Consulta')),
                ('puerta_entrada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Puerta de Entrada / Ruta Prediagnóstica')),
                ('resumen_clinico', models.TextField(blank=True, null=True, verbose_name='Resumen Clínico')),
                ('notas_adicionales', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_impresion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Impresión')),
                ('medico_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historias_clinicas_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas', to='pacientes.paciente')),
                ('usuario_registra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
