# Generated by Django 5.2.8 on 2025-11-14 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='numero_historia',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nro. Historia'),
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='historias.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dosis', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosis')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='historias.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField()),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='historias.historiaclinica')),
            ],
        ),
    ]
