# Generated by Django 5.2.8 on 2025-11-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0002_alter_historiaclinica_numero_historia_diagnostico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='dosis',
        ),
    ]
