# Generated by Django 5.2.8 on 2025-12-03 00:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0003_remove_medicamento_dosis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiaclinica',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Historia Clínica', 'verbose_name_plural': 'Historias Clínicas'},
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha_apertura',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha automática de apertura de la historia clínica.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hora_ingreso',
            field=models.TimeField(auto_now_add=True, verbose_name='Hora de Ingreso'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.CharField(default='PROGRAMADA', max_length=50)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='historias.historiaclinica')),
            ],
        ),
    ]
