# Generated by Django 5.2.8 on 2025-12-05 01:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0004_alter_historiaclinica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='codigo_cie10',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='CIE-10'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='diagnosticos',
            field=models.JSONField(blank=True, null=True, verbose_name='Diagnósticos (CIE-10)'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='examen_fisico',
            field=models.TextField(blank=True, null=True, verbose_name='Examen físico'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='fc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia cardiaca (FC)'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='fr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia respiratoria (FR)'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='medicamentos',
            field=models.TextField(blank=True, null=True, verbose_name='Medicamentos / Prescripción'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='plan_manejo',
            field=models.TextField(blank=True, null=True, verbose_name='Plan de manejo'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='recomendaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Recomendaciones'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='revision_sistemas',
            field=models.JSONField(blank=True, null=True, verbose_name='Revisión por sistemas'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='saturacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Saturación (%)'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='sintomas_principales',
            field=models.TextField(blank=True, null=True, verbose_name='Síntomas principales'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='ta_sist',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='TA sistólica/diastólica'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='talla',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talla (cm)'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='tiempo_evolucion',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Tiempo de evolución'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='tratamiento_previo',
            field=models.TextField(blank=True, null=True, verbose_name='Tratamiento previo'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_rel', to='historias.historiaclinica'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_apertura',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_rel', to='historias.historiaclinica'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='HistoriaAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='historias/adjuntos/%Y/%m/%d/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='historias.historiaclinica')),
            ],
        ),
    ]
